const apiURL = import.meta.env.VITE_APP_API_URL
export const urlUsuarios = `${apiURL}/usuarios`
export const urlCalidad = `${apiURL}/calidad`
export const urlDeposito = `${apiURL}/deposito`
export const urlCategoria = `${apiURL}/categoria`
export const urlUbicacion = `${apiURL}/ubicacion`
export const urlMovimiento = `${apiURL}/movimiento`
export const urlProducto = `${apiURL}/producto`
export const urlTipoProducto = `${apiURL}/tipoProducto`
export const urlTransportista = `${apiURL}/transportista`
// export const urlCuentas = `${apiURL}/cuentas`
// export const urlRatings = `${apiURL}/rating`